import type { Property } from "../types.js";

export const SEED_PROPERTIES: Property[] = [
  {
    id: "oz-001",
    title: "Premium CBD Office Tower",
    address: "100 Collins Street",
    suburb: "Melbourne",
    state: "VIC",
    postcode: "3000",
    type: "office",
    listingType: "lease",
    price: 850,
    priceUnit: "sqm/year",
    area: 420,
    parking: 8,
    floors: 1,
    featured: true,
    description:
      "Prestigious Collins Street address with panoramic city views. Fully fitted open-plan layout with meeting rooms, kitchenette, and 24/7 building access. Ideal for professional services firms.",
    amenities: ["24/7 Access", "Lift Access", "Air Conditioning", "NBN Fibre", "Meeting Rooms", "Kitchenette"],
    agent: { name: "Sarah Mitchell", phone: "03 9000 1200", email: "sarah@ozbiz.com.au" },
    image: "office-melbourne",
  },
  {
    id: "oz-002",
    title: "Martin Place Retail Frontage",
    address: "45 Martin Place",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    type: "retail",
    listingType: "lease",
    price: 1200,
    priceUnit: "sqm/year",
    area: 185,
    parking: 0,
    floors: 1,
    featured: true,
    description:
      "High-foot-traffic retail space in the heart of Sydney CBD. Glass frontage with excellent natural light. Previously operated as a premium café — grease trap and commercial kitchen infrastructure in place.",
    amenities: ["Street Frontage", "Grease Trap", "Air Conditioning", "Storage Room", "Disabled Access"],
    agent: { name: "James Chen", phone: "02 8000 3400", email: "james@ozbiz.com.au" },
    image: "retail-sydney",
  },
  {
    id: "oz-003",
    title: "Eagle Farm Logistics Hub",
    address: "22 Industrial Avenue",
    suburb: "Eagle Farm",
    state: "QLD",
    postcode: "4009",
    type: "warehouse",
    listingType: "lease",
    price: 145,
    priceUnit: "sqm/year",
    area: 2800,
    parking: 20,
    floors: 1,
    featured: true,
    description:
      "Modern warehouse with 8m clear height, dual roller doors, and container-height loading dock. Minutes from Port of Brisbane and airport. Office mezzanine included.",
    amenities: ["Loading Dock", "Container Access", "Office Mezzanine", "3-Phase Power", "Security Fencing", "Sprinkler System"],
    agent: { name: "Michael Torres", phone: "07 3000 5600", email: "michael@ozbiz.com.au" },
    image: "warehouse-brisbane",
  },
  {
    id: "oz-004",
    title: "Subiaco Medical Suites",
    address: "88 Hay Street",
    suburb: "Subiaco",
    state: "WA",
    postcode: "6008",
    type: "office",
    listingType: "lease",
    price: 680,
    priceUnit: "sqm/year",
    area: 240,
    parking: 6,
    floors: 1,
    featured: false,
    description:
      "Purpose-built medical suites with reception area, 4 treatment rooms, and sterilisation room. Compliant with healthcare building standards. Close to Subiaco Hospital.",
    amenities: ["Medical Fit-out", "Reception Area", "Disabled Access", "Lift Access", "Air Conditioning", "Parking"],
    agent: { name: "Emma Walsh", phone: "08 6000 7800", email: "emma@ozbiz.com.au" },
    image: "office-perth",
  },
  {
    id: "oz-005",
    title: "North Adelaide Heritage Conversion",
    address: "15 Brougham Place",
    suburb: "North Adelaide",
    state: "SA",
    postcode: "5006",
    type: "mixed-use",
    listingType: "sale",
    price: 2400000,
    priceUnit: "total",
    area: 520,
    parking: 4,
    floors: 2,
    featured: false,
    description:
      "Stunning heritage building converted to boutique office and ground-floor retail. Exposed brick, timber floors, and original façade. Strong rental history with long-term tenants.",
    amenities: ["Heritage Character", "Dual Tenancy", "Street Frontage", "Air Conditioning", "Alarm System"],
    agent: { name: "David Nguyen", phone: "08 8000 9100", email: "david@ozbiz.com.au" },
    image: "mixed-adelaide",
  },
  {
    id: "oz-006",
    title: "Southbank Creative Studio",
    address: "3 Riverside Quay",
    suburb: "Southbank",
    state: "VIC",
    postcode: "3006",
    type: "office",
    listingType: "lease",
    price: 520,
    priceUnit: "sqm/year",
    area: 310,
    parking: 4,
    floors: 1,
    featured: false,
    description:
      "Light-filled creative space with exposed ceilings, polished concrete floors, and Yarra River views. Open plan with breakout areas. Popular with agencies and tech startups.",
    amenities: ["River Views", "Open Plan", "Kitchenette", "Bike Storage", "NBN Fibre", "Balcony"],
    agent: { name: "Sarah Mitchell", phone: "03 9000 1200", email: "sarah@ozbiz.com.au" },
    image: "office-southbank",
  },
  {
    id: "oz-007",
    title: "Parramatta Corporate Campus",
    address: "200 George Street",
    suburb: "Parramatta",
    state: "NSW",
    postcode: "2150",
    type: "office",
    listingType: "lease",
    price: 480,
    priceUnit: "sqm/year",
    area: 1500,
    parking: 30,
    floors: 2,
    featured: true,
    description:
      "A-grade office space in Parramatta's growing commercial precinct. Full floor plate available with fit-out allowance. Walking distance to Parramatta station and Westfield.",
    amenities: ["End of Trip Facilities", "Lift Access", "Café in Building", "NBN Fibre", "Meeting Rooms", "Secure Parking"],
    agent: { name: "James Chen", phone: "02 8000 3400", email: "james@ozbiz.com.au" },
    image: "office-parramatta",
  },
  {
    id: "oz-008",
    title: "Fortitude Valley Food Precinct",
    address: "12 Brunswick Street",
    suburb: "Fortitude Valley",
    state: "QLD",
    postcode: "4006",
    type: "retail",
    listingType: "lease",
    price: 950,
    priceUnit: "sqm/year",
    area: 120,
    parking: 2,
    floors: 1,
    featured: false,
    description:
      "Vibrant retail tenancy in Brisbane's entertainment district. Perfect for restaurant, bar, or hospitality concept. Exhaust infrastructure and liquor licence transfer available.",
    amenities: ["Exhaust System", "Outdoor Seating", "Grease Trap", "Storage", "High Ceilings"],
    agent: { name: "Michael Torres", phone: "07 3000 5600", email: "michael@ozbiz.com.au" },
    image: "retail-brisbane",
  },
  {
    id: "oz-009",
    title: "Welshpool Industrial Estate",
    address: "5 Welshpool Road",
    suburb: "Welshpool",
    state: "WA",
    postcode: "6106",
    type: "industrial",
    listingType: "sale",
    price: 1850000,
    priceUnit: "total",
    area: 3200,
    parking: 15,
    floors: 1,
    featured: false,
    description:
      "Freehold industrial property with office component and hardstand yard. Suitable for manufacturing, distribution, or trade services. Crane rail installed.",
    amenities: ["Crane Rail", "Hardstand Yard", "Office Component", "3-Phase Power", "B-Double Access"],
    agent: { name: "Emma Walsh", phone: "08 6000 7800", email: "emma@ozbiz.com.au" },
    image: "industrial-perth",
  },
  {
    id: "oz-010",
    title: "Canberra Government Precinct",
    address: "50 London Circuit",
    suburb: "Canberra",
    state: "ACT",
    postcode: "2601",
    type: "office",
    listingType: "lease",
    price: 590,
    priceUnit: "sqm/year",
    area: 680,
    parking: 12,
    floors: 1,
    featured: false,
    description:
      "Secure office space in Canberra CBD, ideal for government contractors and professional services. DDA compliant with after-hours access and basement parking.",
    amenities: ["DDA Compliant", "Basement Parking", "After Hours Access", "Security System", "Meeting Rooms"],
    agent: { name: "Lisa Park", phone: "02 6000 4500", email: "lisa@ozbiz.com.au" },
    image: "office-canberra",
  },
  {
    id: "oz-011",
    title: "Docklands Waterfront Office",
    address: "800 Bourke Street",
    suburb: "Docklands",
    state: "VIC",
    postcode: "3008",
    type: "office",
    listingType: "lease",
    price: 620,
    priceUnit: "sqm/year",
    area: 890,
    parking: 15,
    floors: 1,
    featured: false,
    description:
      "Waterfront office with harbour views in Melbourne's Docklands precinct. Modern building with end-of-trip facilities and direct tram access to Southern Cross Station.",
    amenities: ["Water Views", "End of Trip", "Tram at Door", "NBN Fibre", "Concierge", "Gym in Building"],
    agent: { name: "Sarah Mitchell", phone: "03 9000 1200", email: "sarah@ozbiz.com.au" },
    image: "office-docklands",
  },
  {
    id: "oz-012",
    title: "Hobart Waterfront Retail",
    address: "1 Salamanca Place",
    suburb: "Hobart",
    state: "TAS",
    postcode: "7000",
    type: "retail",
    listingType: "lease",
    price: 780,
    priceUnit: "sqm/year",
    area: 95,
    parking: 0,
    floors: 1,
    featured: false,
    description:
      "Iconic Salamanca Place retail tenancy with sandstone façade and Saturday Market exposure. Perfect for boutique retail, gallery, or specialty food concept.",
    amenities: ["Heritage Façade", "Market Exposure", "Street Frontage", "Storage Cellar"],
    agent: { name: "Tom Bradley", phone: "03 6000 3300", email: "tom@ozbiz.com.au" },
    image: "retail-hobart",
  },
];